### ISSUE TITLE
@include not working in firefox

### ISSUE THREAD

**Issue by Nafania** [KangoExtensions/kango#26]
I have a content script
In header of it i have

// ==UserScript==
// @name kinopoisk
// @include http://www.kinopoisk.ru
// ==/UserScript==

kango.console.log('kinopoisk loaded');
....

in extension_info.js i have 
    "content_scripts": [
        "/js/kinopoisk.js"
    ]

but firefox won't load this script. I don't have 'kinopoisk loaded' in console, but chrome and opera works fine.

**Comment by akrylysov** [comment]
Works for me. Are you trying to view logs in Web Console or in Error Console (you should use second http://kangoextensions.com/docs/api-reference/kango-console.html#firefox). If it still doesn't works - please send your XPI to extensions@kangoextensions.com

**Comment by Nafania** [comment]
In error console of course. I sent you xpi.

**Comment by akrylysov** [comment]
Seems Firefox version of Kango don't recognize path with front slash. Replace "/js/kinomania.js" etc. to "js/kinomania.js" and it will works.
Btw, since Kango 1.0 you can load jQuery and other libs using @require header key (see https://github.com/KangoExtensions/kango-samples/blob/master/ChristmasTree/src/common/tree.js).

**Comment by Nafania** [comment]
Спасибо, теперь все отлично.
Я думаю, что такой момент стоит указать в документации.

Большое вам спасибо за фреймворк.

07.12.2012 18:49, Artem Krylysov пишет:
